%% This script produces Figure 2 from Sharp et al. (in prep)
% It plots pCO2 at the CCE2 mooring, along with pCO2 from corresponding
% grid cells in RFR-CCS, RFR-CCS-Eval, and Laruelle et al. (2017).

latlims = [latmin latmax];
lonlims = [lonmin lonmax];
pos = [0 0 1 0.5];
titlesz = 28;
fontsz = 22;

% Match latitude in climatology
latidx = ...
    find(abs(SOCATv2021_grid.latitude(1,:,1)-mean(MOORING.CCE2.lat,'omitnan')) == ...
    min(min(abs(SOCATv2021_grid.latitude(1,:,1)-mean(MOORING.CCE2.lat,'omitnan')))));
lonidx = ...
    find(abs(SOCATv2021_grid.longitude(:,1,1)-mean(MOORING.CCE2.lon,'omitnan')) == ...
    min(min(abs(SOCATv2021_grid.longitude(:,1,1)-mean(MOORING.CCE2.lon,'omitnan')))));

% Determine mooring month since 1998
MOORING.CCE2.month_since_1998 = ...
    (MOORING.CCE2.date(:,1)-1998).*12 + MOORING.CCE2.date(:,2);

% Determine means of each month since 1998
MOORING.CCE2.pCO2SW_mon = nan(max(SOCATv2021_grid.month_since_1998),1);
for m=1:max(SOCATv2021_grid.month_since_1998)
    MOORING.CCE2.month_since_1998_mon(m) = m;
    MOORING.CCE2.pCO2SW_mon_mean(m) = ...
        mean(MOORING.CCE2.pCO2SW(MOORING.CCE2.month_since_1998==m),'omitnan');
    MOORING.CCE2.pCO2SW_mon_std(m)  = ...
        std(MOORING.CCE2.pCO2SW(MOORING.CCE2.month_since_1998==m),'omitnan');
end

% Plot climatology pCO2 and mooring measured pCO2
figure; box on;
set(gcf,'units','normalized','outerposition',pos);
set(gca,'fontsize',fontsz);
title('CCE2','fontsize',titlesz);
hold on
date = datenum([repmat(1998,276,1) SOCATv2021_grid.month_since_1998 ones(276,1)]);
% borders of uncertainty envelopes
t1=plot(date,squeeze(SOCATv2021_grid.pco2_RF(lonidx,latidx,:)) + ...
    U_tot_coast,'linewidth',1,'Color',clr1);
b1=plot(date,squeeze(SOCATv2021_grid.pco2_RF(lonidx,latidx,:)) - ...
    U_tot_coast,'linewidth',1,'Color',clr1);
t2=plot(date,squeeze(SOCATv2021_grid.pco2_RF_validate(lonidx,latidx,:)) + ...
    U_tot_coast,'linewidth',1,'Color',clr4);
b2=plot(date,squeeze(SOCATv2021_grid.pco2_RF_validate(lonidx,latidx,:)) - ...
    U_tot_coast,'linewidth',1,'Color',clr4);
t3=plot(date,MOORING.CCE2.pCO2SW_mon_mean + ...
    MOORING.CCE2.pCO2SW_mon_std,'linewidth',1,'Color','k');
b3=plot(date,MOORING.CCE2.pCO2SW_mon_mean - ...
    MOORING.CCE2.pCO2SW_mon_std,'linewidth',1,'Color','k');
t4=plot(LAR.date,squeeze(LAR.pCO2(lonidx,latidx,:)) + 52.5,...
    'linewidth',1,'Color',clr2);
b4=plot(LAR.date,squeeze(LAR.pCO2(lonidx,latidx,:)) - 52.5,...
    'linewidth',1,'Color',clr2);
% uncertainty envelopes
f1=fill([date;flipud(date)],...
    [squeeze(SOCATv2021_grid.pco2_RF(lonidx,latidx,:)) + U_tot_coast;...
     flipud(squeeze(SOCATv2021_grid.pco2_RF(lonidx,latidx,:)) - U_tot_coast)],...
     clr1,'FaceAlpha',0.15,'LineStyle','none');
f2=fill([date;flipud(date)],...
    [squeeze(SOCATv2021_grid.pco2_RF_validate(lonidx,latidx,:)) + U_tot_coast;...
     flipud(squeeze(SOCATv2021_grid.pco2_RF_validate(lonidx,latidx,:)) - U_tot_coast)],...
     clr4,'FaceAlpha',0.15,'LineStyle','none');
% index to available mooring observations
idx = find(~isnan(MOORING.CCE2.pCO2SW_mon_mean) & ...
    ~isnan(MOORING.CCE2.pCO2SW_mon_std));
a=diff(idx); % differences in index numbers
b=find([a inf]>1); % ends of series
c=diff([0 b]); % lengths of series
d=cumsum(c); % ends of series
idx1 = idx(1);
for n=1:length(d)
    idx2 = idx(d(n));
    f3=fill([date(idx1:idx2);...
        flipud(date(idx1:idx2))],...
        [MOORING.CCE2.pCO2SW_mon_mean(idx1:idx2) + ...
         MOORING.CCE2.pCO2SW_mon_std((idx1:idx2)),...
         fliplr(MOORING.CCE2.pCO2SW_mon_mean(idx1:idx2) - ...
         MOORING.CCE2.pCO2SW_mon_std(idx1:idx2))],...
         'k','FaceAlpha',0.15,'LineStyle','none');
     if n < length(d)
         idx1 = idx(d(n)+1)
     end
end
f4=fill([LAR.date;flipud(LAR.date)],...
    [squeeze(LAR.pCO2(lonidx,latidx,:)) + 52.5;...
     flipud(squeeze(LAR.pCO2(lonidx,latidx,:)) - 52.5)],...
     clr2,'FaceAlpha',0.15,'LineStyle','none');
% center lines
p1=plot(date,squeeze(SOCATv2021_grid.pco2_RF(lonidx,latidx,:)),'linewidth',4,'Color',clr1);
s1=scatter(date,squeeze(SOCATv2021_grid.pco2_RF(lonidx,latidx,:)),100,'o',...
    'MarkerFaceColor',clr1,'MarkerEdgeColor','none');
p2=plot(date,squeeze(SOCATv2021_grid.pco2_RF_validate(lonidx,latidx,:)),':','linewidth',4,'Color',clr4);
s2=scatter(date,squeeze(SOCATv2021_grid.pco2_RF_validate(lonidx,latidx,:)),100,'o',...
    'MarkerFaceColor',clr4,'MarkerEdgeColor','none');
p3=plot(date,MOORING.CCE2.pCO2SW_mon_mean,'k','linewidth',4);
s3=scatter(date,MOORING.CCE2.pCO2SW_mon_mean,100,'s',...
    'MarkerFaceColor','k','MarkerEdgeColor','none');
p4=plot(LAR.date,squeeze(LAR.pCO2(lonidx,latidx,:)),'Color',clr2,'linewidth',4);
s4=scatter(LAR.date,squeeze(LAR.pCO2(lonidx,latidx,:)),100,'^',...
    'MarkerFaceColor',clr2,'MarkerEdgeColor','none');
% dummy symbols for legends
lg1 = plot(nan,nan, 'o-','linewidth',4,'MarkerSize',10,'MarkerEdgeColor','none',...
    'Color',clr1,'MarkerFaceColor',clr1,'DisplayName','RFR-CCS');
lg2 = plot(nan,nan, 'o:','linewidth',4,'MarkerSize',10,'MarkerEdgeColor','none',...
    'Color',clr4,'MarkerFaceColor',clr4,'DisplayName','RFR-CCS-Eval');
lg3 = plot(nan,nan, 's-','linewidth',4,'MarkerSize',10,'MarkerEdgeColor','none',...
    'Color','k','MarkerFaceColor','k','DisplayName','Mooring Observations');
lg4 = plot(nan,nan, '^-','linewidth',4,'MarkerSize',10,'MarkerEdgeColor','none',...
    'Color',clr2,'MarkerFaceColor',clr2,'DisplayName','L17');
% add legend
legend([lg3 lg1 lg2 lg4],'location','northeast',...
                       'box','on','AutoUpdate','off');
% [l,icons]=legend([s3 s1 s2 s4],{'Mooring Observations'...
%                        'RFR-CCS'...
%                        'RFR-CCS-Eval'...
%                        'L17'},'location','northeast',...
%                        'box','on','AutoUpdate','off');
ylabel('{\itp}CO_{2(sw)} (\muatm)');
xlabel('Year');
datetick('x','yyyy');
xlim([min(date(~isnan(MOORING.CCE2.pCO2SW_mon_mean))) ...
      max(date(~isnan(MOORING.CCE2.pCO2SW_mon_mean)))]);
ylim([250 600]);

%% Export figure
exportgraphics(gcf,'Figures/Figure2.png');

