%% This script produces Figure 5 from Sharp et al. (in prep)

%% Mooring names:
moornames  = {'WA' 'CCE1' 'CCE2' 'NH10' 'LaPush'};
moornames2 = {'Cape Elizabeth' 'CCE1' 'CCE2' 'NH10' 'Chá bâ'};
moornames3 = {'Cape Elizabeth (2006-17)' 'CCE1 (2008-17)' 'CCE2 (2010-17)' 'NH10 (2014-17)' 'Chá bâ (2010-17)'};

% Initialize figure

latlims = [latmin latmax];
lonlims = [lonmin lonmax];
ocncol = [1 1 1];
lndcol = [0.94 0.88 0.8];
titlesz = 18;
labelsz = 16;

figure;
set(gcf,'units','normalized','outerposition',[0 0 0.5 1])
tl = axes('Position',[0.1 0.70 0.375 0.25],'Box','on');
tr = axes('Position',[0.6 0.70 0.375 0.25],'Box','on');
ml = axes('Position',[0.1 0.375 0.375 0.25],'Box','on');
mr = axes('Position',[0.6 0.375 0.375 0.25],'Box','on');
bl = axes('Position',[0.1 0.05 0.375 0.25],'Box','on');

aaxx = [tl tr ml mr bl];

% Start loop
for n=1:numel(moornames)
    
    %% Establish axis
    axes(aaxx(n)); hold on;
    
    %% Find closest point on grid to lat-lon
    latidx = ...
        find(abs(SOCATv2021_grid.latitude(1,:,1)-mean(MOORING.(moornames{n}).lat,'omitnan')) == ...
        min(min(abs(SOCATv2021_grid.latitude(1,:,1)-mean(MOORING.(moornames{n}).lat,'omitnan')))));
    lonidx = ...
        find(abs(SOCATv2021_grid.longitude(:,1,1)-mean(MOORING.(moornames{n}).lon,'omitnan')) == ...
        min(min(abs(SOCATv2021_grid.longitude(:,1,1)-mean(MOORING.(moornames{n}).lon,'omitnan')))));

    %% Determine monthly means for one annual cycle, across mooring available years
    % Pre-allocate
    SOCATv2021_grid.pco2_RF_clim_moor= ...
        nan(size(SOCATv2021_grid.lon,1),size(SOCATv2021_grid.lat,2),12);
    SOCATv2021_grid.pco2_RF_clim_moor_std = ...
        nan(size(SOCATv2021_grid.lon,1),size(SOCATv2021_grid.lat,2),12);
    % Determine monthly means for one annual cycle
    for m = 1:12
        SOCATv2021_grid.pco2_RF_clim_moor(:,:,m) = ...
            mean(SOCATv2021_grid.pco2_RF(:,:,1:12:end),3,'omitnan');
        SOCATv2021_grid.pco2_RF_clim_moor_std(:,:,m) = ...
            std(SOCATv2021_grid.pco2_RF(:,:,1:12:end),0,3,'omitnan');
    end

    %% Plot pCO2 from different sources:
    title(moornames3{n},'FontSize',titlesz);
    set(gca,'fontsize',labelsz);
    
    % standard deviations of monthly mooring means
    MOORING.(moornames{n}).pCO2SW_monthly_std = nan(12,1);
    for m = 1:12
       MOORING.(moornames{n}).pCO2SW_monthly_std(m) = ...
           std(MOORING.(moornames{n}).pCO2SW_mon_mean(m:12:end),[],'omitnan');
    end
    
    % borders of uncertainty envelopes
    t1=plot(1:12,(MOORING.(moornames{n}).pCO2SW_monthly(:,1)-...
        mean(MOORING.(moornames{n}).pCO2SW_monthly(:,1))) + ...
        MOORING.(moornames{n}).pCO2SW_monthly_std,'linewidth',1,'Color','k');
    b1=plot(1:12,(MOORING.(moornames{n}).pCO2SW_monthly(:,1)-...
        mean(MOORING.(moornames{n}).pCO2SW_monthly(:,1))) - ...
        MOORING.(moornames{n}).pCO2SW_monthly_std,'linewidth',1,'Color','k');
    t2=plot(1:12,(squeeze(LAR.pCO2_mon(lonidx,latidx,:))-...
        mean(squeeze(LAR.pCO2_mon(lonidx,latidx,:)))) + ...
        squeeze(LAR.pCO2_mon_std(lonidx,latidx,:)),'linewidth',1,'Color',clr2);
    b2=plot(1:12,(squeeze(LAR.pCO2_mon(lonidx,latidx,:))-...
        mean(squeeze(LAR.pCO2_mon(lonidx,latidx,:)))) - ...
        squeeze(LAR.pCO2_mon_std(lonidx,latidx,:)),'linewidth',1,'Color',clr2);
    t3=plot(1:12,(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))-...
        mean(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:)))) + ...
        squeeze(SOCATv2021_grid.pco2_RF_clim_std_2015(lonidx,latidx,:)),'linewidth',1,'Color',clr1);
    b3=plot(1:12,(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))-...
        mean(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:)))) - ...
        squeeze(SOCATv2021_grid.pco2_RF_clim_std_2015(lonidx,latidx,:)),'linewidth',1,'Color',clr1);

    % uncertainty envelopes
    fill([1:12 fliplr(1:12)],[[(MOORING.(moornames{n}).pCO2SW_monthly(:,1)-...
        mean(MOORING.(moornames{n}).pCO2SW_monthly(:,1))) + ...
        MOORING.(moornames{n}).pCO2SW_monthly_std]' ...
        [flipud((MOORING.(moornames{n}).pCO2SW_monthly(:,1)-...
        mean(MOORING.(moornames{n}).pCO2SW_monthly(:,1))) - ...
        MOORING.(moornames{n}).pCO2SW_monthly_std)]'],...
        'k','FaceAlpha',0.15,'LineStyle','none');
    fill([1:12 fliplr(1:12)],[[(squeeze(LAR.pCO2_mon(lonidx,latidx,:))-...
        mean(squeeze(LAR.pCO2_mon(lonidx,latidx,:)))) + ...
        squeeze(LAR.pCO2_mon_std(lonidx,latidx,:))]' ...
        [flipud((squeeze(LAR.pCO2_mon(lonidx,latidx,:))-...
        mean(squeeze(LAR.pCO2_mon(lonidx,latidx,:)))) - ...
        squeeze(LAR.pCO2_mon_std(lonidx,latidx,:)))]'],...
        clr2,'FaceAlpha',0.15,'LineStyle','none');
    fill([1:12 fliplr(1:12)],[[(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))-...
        mean(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:)))) + ...
        squeeze(SOCATv2021_grid.pco2_RF_clim_std_2015(lonidx,latidx,:))]' ...
        [flipud((squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))-...
        mean(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:)))) - ...
        squeeze(SOCATv2021_grid.pco2_RF_clim_std_2015(lonidx,latidx,:)))]'],...
        clr1,'FaceAlpha',0.15,'LineStyle','none');
    
    % zero line
    plot([0 13],[0 0],':','LineWidth',3,'Color','k');
    
    % center lines
    plot(1:12,MOORING.(moornames{n}).pCO2SW_monthly(:,1)-...
        mean(MOORING.(moornames{n}).pCO2SW_monthly(:,1)),'-o',...
        'LineWidth',3,'Color','k');
    scatter(1:12,MOORING.(moornames{n}).pCO2SW_monthly(:,1)-...
        mean(MOORING.(moornames{n}).pCO2SW_monthly(:,1)),100,'o',...
        'MarkerEdgeColor','none','MarkerFaceColor','k',...
        'LineWidth',1);
    plot(1:12,squeeze(LAND.pCO2(lonidx,latidx,:))-...
        mean(squeeze(LAND.pCO2(lonidx,latidx,:))),'-o',...
        'LineWidth',3,'Color',clr3);
    scatter(1:12,squeeze(LAND.pCO2(lonidx,latidx,:))-...
        mean(squeeze(LAND.pCO2(lonidx,latidx,:))),100,'o',...
        'MarkerEdgeColor','none','MarkerFaceColor',clr3,...
        'LineWidth',1);
    plot(1:12,squeeze(LAR.pCO2_mon(lonidx,latidx,:))-...
        mean(squeeze(LAR.pCO2_mon(lonidx,latidx,:))),'-o',...
        'LineWidth',3,'Color',clr2);
    scatter(1:12,squeeze(LAR.pCO2_mon(lonidx,latidx,:))-...
        mean(squeeze(LAR.pCO2_mon(lonidx,latidx,:))),100,'o',...
        'MarkerEdgeColor','none','MarkerFaceColor',clr2,...
        'LineWidth',1);
    plot(1:12,squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))-...
        mean(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))),'-o',...
        'LineWidth',3,'Color',clr1);
    scatter(1:12,squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))-...
        mean(squeeze(SOCATv2021_grid.pco2_RF_clim_2015(lonidx,latidx,:))),100,'o',...
        'MarkerEdgeColor','none','MarkerFaceColor',clr1,...
        'LineWidth',1);
    
    % dummy symbols for legends
    mo=plot(nan,nan, 'o-','linewidth',4,'MarkerSize',12,'MarkerEdgeColor','none',...
    'Color','k','MarkerFaceColor','k','DisplayName','Mooring');
    land=plot(nan,nan, 'o-','linewidth',4,'MarkerSize',12,'MarkerEdgeColor','none',...
    'Color',clr3,'MarkerFaceColor',clr3,'DisplayName','L20');
    lar=plot(nan,nan, 'o-','linewidth',4,'MarkerSize',12,'MarkerEdgeColor','none',...
    'Color',clr2,'MarkerFaceColor',clr2,'DisplayName','L17');
    rf=plot(nan,nan, 'o-','linewidth',4,'MarkerSize',12,'MarkerEdgeColor','none',...
    'Color',clr1,'MarkerFaceColor',clr1,'DisplayName','RFR-CCS-clim');
    
    %% Figure properties:
    xlim([0.5 12.5]);
    ylim([-150 150]);
    ylabel('{\itp}CO_{2} Anomaly (\muatm)');
    xticks([1:12]);
    xticklabels({'J' 'F' 'M' 'A' 'M' 'J' 'J' 'A' 'S' 'O' 'N' 'D'});
end

%% Legends for figures:
br = axes('Position',[0.6 0.05 0.375 0.25],'Box','off');
hl=legend(br,[mo land lar rf],{'Mooring' 'L20' 'L17' 'RFR-CCS-clim'});
set(hl,'Position', [0.65 0.075 0.225 0.2],'fontsize',28);
%l = findobj(l,'Type','Line');
%set(l,'MarkerSize',10);
br.Visible = 'off';

%% Export figure
exportgraphics(gcf,['Figures/Figure5.png']);
